name: sql-course
channels:
  - conda-forge
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - keyring
  - pandas
  - python-duckdb
  - python-dotenv
  - pip
  - ipywidgets
  - pip:
    - jupyter-book
    - pkgmt>=0.1.7
    - duckdb==0.8.0
    - duckdb-engine==0.9.0
    - jupysql-plugin
    - urllib3==1.26.6
